// 4 bildirim türünün TR/EN/ES içerikleri — tek yerde. Kullanıcı raporu: bildirimler
// kullanıcının seçtiği arayüz dilinden BAĞIMSIZ, her zaman Türkçe gidiyordu (bkz.
// common.js'teki YENİ `getLanguageCode(uid)` — `users/{uid}/state/languageCode`'u okuyup
// `tr`/`en`/`es` döner). Çeviriler burada BİREBİR çeviri değil, `lib/data/zibo_messages.dart`
// ile AYNI felsefeyle (Zibo'nun sıcak/samimi tonu, "Kanka"/"Buddy"/"Amigo" hitabı) uyarlandı.

// Günlük Motivasyon — 2026 bug düzeltmesi: bu havuz eskiden yalnızca 8/dil'lik küçük,
// bağımsız bir alt küme kullanıyordu ("sunucu tarafında tam 279'luk havuzla senkron
// tutulmuyor, küçük temsili bir alt küme kullanılıyor" — bkz. bu dosyanın git geçmişi) —
// gerçek kullanıcı raporu ("bildirimlerde hep aynı motivasyon cümleleri tekrar ediyor")
// bunun kök nedeniydi: 8 sözlük bir havuzdan rastgele seçim yapınca birkaç bildirimde bir
// aynı söz tekrar tekrar geliyordu. Artık `lib/data/zibo_messages.dart`'taki (Ana Sayfa'nın
// KENDİSİNİN kullandığı) TAM 279'luk TR/EN/ES havuzuyla BİREBİR AYNI/senkron —
// `tool/generate_content_js_daily_motivation.dart` (YENİ, tekrar çalıştırılabilir betik) ile
// üretildi, elle kopyalanmadı. Üç dil de BİREBİR AYNI sayıda (279) söz içeriyor ki
// `getLanguageCode` hangi dili dönerse dönsün aynı çeşitlilikte seçim yapılabilsin.
const daily_motivation = {
  tr: [
    "Kalktın mı yataktan yoksa hâlâ pazarlık mı ediyorsun kendinle?",
    "Bugün de dünyaya \"ben buradayım\" de.",
    "Kahveni al, planını yap, hadi başla.",
    "Tembellik seni sevmiyor kanka, ben seviyorum.",
    "Bir adım at, gerisi kendi gelir.",
    "Bugün zor olabilir ama sen zordan zor değilsin.",
    "Kalk hadi, güneş bile senden erken kalktı.",
    "Ertelemek en sevdiğin spor, biliyorum ama bugün olmaz.",
    "Sen yapmazsan kim yapacak, ben mi?",
    "Bugün küçük bir şey başar, yeter.",
    "Zor günler geçer, sen kalırsın.",
    "Bugün kendine kızma, yarın telafi edersin.",
    "Hadi kanka, bir de sen inan kendine.",
    "Bugün \"yapamam\" deme, \"yapmadım\" de, ikisi farklı.",
    "Az uyudun biliyorum ama bahane bu değil.",
    "Sen düşündüğünden güçlüsün, ben biliyorum.",
    "Bugün telefonu bırak, hayat orada değil.",
    "Küçük adımlar da adımdır, unutma.",
    "Bugün biri sana kötü davranırsa, sen iyi kal.",
    "Kanka bugün suyunu içtin mi, yoksa yine unuttun mu?",
    "Zorlanıyorsan iyi gidiyorsun demektir.",
    "Bugün bir şeyi bitirmeden yatma.",
    "Sen pes etmeyi bilmiyorsun, ben biliyorum.",
    "Bugün kendine \"aferin\" de, hak ettin.",
    "Yorgunsun ama bitmedin, farkı biliyorsun değil mi?",
    "Bugün gülümse, bedava.",
    "Kanka bugün de mi erteledin? Tamam, yarın kesin.",
    "Küçük bir mola ver ama pes etme.",
    "Bugün birine iyilik yap, sana da geri döner.",
    "Sen bugün buradaysan, dün de kazandın demektir.",
    "Zor bir gün mü? Ben yanındayım.",
    "Bugün kendinle gurur duy, sebep aramana gerek yok.",
    "Hadi kanka, bugün rekor kırma günü.",
    "Bugün bir \"hayır\" de, kendine iyilik yap.",
    "Yavaş git ama durma.",
    "Bugün ne olursa olsun, akşam kendine teşekkür et.",
    "Sen bilirsin ama ben hep buradayım.",
    "Kanka bugün de telefonla mı başladın güne? Olsun, şimdi kalk.",
    "Bugün bir hedefe bir adım daha yaklaş.",
    "Zor olan şey değerlidir, unutma.",
    "Bugün kendine iyi bak, kimse senin kadar önemli değil.",
    "Hadi, bugünü dünden iyi yap.",
    "Bugün bir şeyi öğren, küçük de olsa.",
    "Sen vazgeçmedin, ben de vazgeçmiyorum.",
    "Kanka bugün planın neydi, hatırlıyor musun?",
    "Bugün biraz da kendine zaman ayır.",
    "Zor işler kolay olsa herkes yapardı.",
    "Bugün kendine bir söz ver, tut onu.",
    "Hadi kanka, bugün de bir şeyler başaracaksın.",
    "Bugün moralin düşükse, bana yaslan, geçer.",
    "Sen bugün buradaysan, savaşı kazanıyorsun demektir.",
    "Kanka erken kalktın mı, yoksa alarm seni mi kalktırdı?",
    "Bugün bir hata yaparsan, düzelt ve devam et.",
    "Zor bir haftaydı biliyorum, bugün nefes al.",
    "Bugün kendine \"yeter artık\" deme, \"biraz daha\" de.",
    "Sen güçlüsün, ben tanığım.",
    "Bugün bir gülümseme dağıt.",
    "Kanka bugün kendine iyi davran, hak ediyorsun.",
    "Zor günler seni şekillendiriyor, unutma.",
    "Bugün bir adım geri atma, ileri git.",
    "Hadi kanka, bugünün kahramanı sensin.",
    "Bugün kendine inanmayan biri varsa, o sen olma.",
    "Sen bugün de ayaktasın, bu bile bir zafer.",
    "Kanka bugün suyunu, uykunu, kendini ihmal etme.",
    "Zor olan bitmez ama sen bitmezsin.",
    "Bugün küçük bir iyilik yap kendine.",
    "Hadi, bugün de mücadele günü.",
    "Sen bugün de buradasın, bu yeter bana.",
    "Kanka bugün kendine kızmadan bitir günü.",
    "Zor bir gün geçirdiysen, yarın yeni bir gün.",
    "Bugün bir şeyi tamamla, ne olursa olsun.",
    "Hadi kanka, bugün de bir adım daha at.",
    "Sen bugün de mücadele ettin, farkında mısın?",
    "Kanka bugün kendine iyi bir şey söyle.",
    "Zor işleri kolaylaştıran şey sabırdır, sende var.",
    "Bugün kendine güven, ben güveniyorum zaten.",
    "Hadi, bugün de bir şeyler öğren.",
    "Sen bugün de pes etmedin, bu yeterli.",
    "Kanka bugün kendine bir mola hak et.",
    "Zor bir gün olabilir ama sen zorlu birisin.",
    "Bugün bir hedefe daha yaklaştın, farkında mısın?",
    "Hadi kanka, bugün seni izliyorum, iyi git.",
    "Sen bugün de kalktın, bu bile bir başarı.",
    "Kanka bugün kendine \"yapabilirim\" de.",
    "Zor günler geçer, sen kalıcısın.",
    "Bugün bir şeyi bırak, bir şeyi başlat.",
    "Hadi, bugün de kendine değer ver.",
    "Sen bugün de savaştın, farkında mısın?",
    "Kanka bugün kendine bir teşekkür borçlusun.",
    "Zor bir hafta geçirdiysen, bugün nefes al.",
    "Bugün bir adım at, korkma.",
    "Hadi kanka, bugün de bir şeyler değişecek.",
    "Sen bugün de ayaktasın, bu bile yeter.",
    "Kanka bugün kendine iyi bak, ben izliyorum.",
    "Zor işler seni güçlendirir, unutma.",
    "Bugün bir gülümseme ver, bedava.",
    "Hadi, bugün de bir şeyler kazan.",
    "Sen bugün de mücadele ediyorsun, farkında mısın?",
    "Kanka bugün kendine bir söz ver.",
    "Zor bir gün olabilir ama sen zorluklardan güçlü çıkarsın.",
    "Kanka bugün de ayaktasın, bu bile bir şey.",
    "Hadi kanka, bugün küçük bir şey dene.",
    "Kanka sen bilirsin ama ben yanındayım.",
    "Bugün zor geçti biliyorum kanka, geçer bu da.",
    "Kanka az kaldı, pes etme.",
    "Sen güçlüsün kanka, unutma bunu.",
    "Kanka bugün kendine iyi bak.",
    "Hadi kanka, bir adım daha at.",
    "Kanka dün de zorlanmıştın ama başardın.",
    "Bugün de mücadele ettin kanka, farkında mısın?",
    "Kanka bir şeyi bitirmeden bırakma bugün.",
    "Sen pes etmeyi bilmiyorsun kanka.",
    "Yorulduysan da devam et kanka.",
    "Kanka bak, gördün mü, yapabiliyormuşsun.",
    "Bugün küçük bir zafer kazan kanka.",
    "Kanka herkesin bir mücadelesi var, sen yalnız değilsin.",
    "Sabret biraz daha kanka, değer.",
    "Kanka bugün bir hedefe yaklaştın.",
    "Kendine inan biraz kanka.",
    "Kanka zor olan bırakmak değil, devam etmek.",
    "Bugün de buradasın kanka, bu bile bir zafer.",
    "Kanka küçük adımlar da adımdır.",
    "Sen düşündüğünden güçlüsün kanka.",
    "Kanka bugün bir şey dene, ne olur ne olmaz.",
    "Az kaldı kanka, hisset bunu.",
    "Kanka bugün yaptığın yarını inşa ediyor.",
    "Kimse mükemmel değil kanka, sen de olmak zorunda değilsin.",
    "Bir adım geri değil kanka, hep ileri.",
    "Kanka zorlandığın an, büyüdüğün andır.",
    "Bugün pes etme kanka, yarın minnettar olacaksın.",
    "Kanka sabır bazen tek silahındır.",
    "Hata yapman seni değersiz yapmaz kanka.",
    "Kanka bugün bir tuğla koy, bina kendi yükselir.",
    "İnanmıyorsan bile devam et kanka, inanç sonra gelir.",
    "Kanka zor günler seni test eder, sen geçersin.",
    "Bir şeyi bitirmeden bırakma bugün kanka.",
    "Yorgunluk geçici kanka, pes etmek kalıcı.",
    "Kanka bugün kendine bir söz ver ve tut onu.",
    "Küçük başarılar da kutlanmayı hak eder kanka.",
    "Kanka nerede olduğunu bilmesen de ilerliyorsun.",
    "Bugün biraz daha sabret kanka.",
    "Herkesin kendi hızı var kanka, sen kendi hızında git.",
    "Kanka bir şeyi öğrenmek asla geç değil.",
    "Bugün bir korkunu yen kanka.",
    "Zorluklar seni şekillendiriyor kanka, unutma.",
    "Kanka kendi yolculuğunu başkasıyla kıyaslama.",
    "Bugün küçük bir zafer kazan kanka, yeter.",
    "Emek boşa gitmez kanka, er ya da geç karşılığını bulur.",
    "Kanka sen bu işi hallederiz diyen birisin, öyle davran.",
    "Bugün bir şeyi tamamla kanka, ne kadar küçük olursa olsun.",
    "Kendine kızmak yerine kendine yol göster kanka.",
    "Zor bir gün geçirdiysen kanka, yarın yeniden başla.",
    "Sen buradaysan kanka, hâlâ mücadele ediyorsun demektir.",
    "Kanka bugün bir adım daha yaklaştın hedefe.",
    "Kusursuz olmak zorunda değilsin kanka, ilerlemek yeter.",
    "Bazen en büyük başarı sadece devam etmektir kanka.",
    "Bugün kendine nazik davran kanka.",
    "Zor olanı yapan farklı sonuç alır kanka.",
    "Bir hedefin varsa kanka, bugün ona bir santim daha yaklaş.",
    "Kendini küçümseme kanka, bildiğinden fazlasını başardın.",
    "Bugün moralin düşükse bile bir şey dene kanka.",
    "Yol uzun olabilir kanka ama sen yürümeye devam ediyorsun.",
    "Küçük bir ilerleme kanka, hiç ilerlememekten iyidir.",
    "Bugün kendine güven biraz daha kanka.",
    "Zorluk seni durdurmasın kanka, sadece yavaşlatsın.",
    "Bir gün kötü geçti diye her şey bitmiş sayılmaz kanka.",
    "Sen her gün biraz daha iyi oluyorsun kanka, fark etmesen bile.",
    "Bugün bir şeyden vazgeçme kanka.",
    "Emin adımlarla yürü kanka, hızlı olmak zorunda değilsin.",
    "Kendine bir şans daha ver kanka.",
    "Bugün bir hata yaptıysan kanka, düzelt ve devam et.",
    "Zor olan şey genelde değerli olandır kanka.",
    "Sen pes etmeyecek kadar güçlüsün kanka.",
    "Bugün küçük bir iyilik yap kendine kanka.",
    "Herkes bir yerden başladı kanka, sen de öylesin.",
    "Bugün bir adım at kanka, korkma.",
    "Zaman senin lehine çalışıyor kanka, sabret.",
    "Kendi hikayeni sen yazıyorsun kanka.",
    "Bugün kendine bir hedef koy kanka, ne olursa olsun küçük bir tane.",
    "Yorulduğunda durmak zayıflık değildir kanka.",
    "Sen buraya kadar geldin kanka, geri dönmek yok.",
    "Bugün bir şeyi başarabileceğine inan kanka.",
    "Zorluklar bitmez kanka ama sen de bitmezsin.",
    "Kendine inanmak bazen tek başlangıç noktasıdır kanka.",
    "Bugün bir adım kanka, yarın bir adım daha.",
    "Küçük değişiklikler zamanla büyük fark yaratır kanka.",
    "Sen sandığından daha dayanıklısın kanka.",
    "Bugün kendine bir teşekkür borçlusun kanka.",
    "Zor bir süreçten geçiyorsan kanka, bu geçici.",
    "Bir şeyi denemek kanka, hiç denememekten iyidir.",
    "Bugün kendi yoluna sadık kal kanka.",
    "Herkesin bir mücadelesi var kanka, sen yalnız değilsin.",
    "Bugün bir hedefe bir tık daha yaklaştın kanka.",
    "Kendini affetmeyi öğren kanka, hata yapmak insanın doğası.",
    "Zor olanı yapmaya devam et kanka, kolay olan seni büyütmez.",
    "Bugün bir şeyi bitirmeden bırakma kanka.",
    "Yolun sonunu göremesen de kanka, yol seni bir yere götürüyor.",
    "Küçük adımların toplamı büyük bir mesafe yapar kanka.",
    "Bugün kendine inanmak için bir sebep bul kanka.",
    "Zorluklar seni yıldırmasın kanka, güçlendirsin.",
    "Kanka bugün bir şey öğren, küçük de olsa.",
    "Sen vazgeçmedin kanka, ben de vazgeçmiyorum.",
    "Bugün biraz da kendine zaman ayır kanka.",
    "Zor işler kolay olsa herkes yapardı kanka.",
    "Kanka bugün kendine bir söz ver, tut onu.",
    "Bugün moralin düşükse kanka, bana yaslan, geçer.",
    "Sen bugün buradaysan kanka, savaşı kazanıyorsun demektir.",
    "Bugün bir hata yaparsan kanka, düzelt ve devam et.",
    "Zor bir haftaydı biliyorum kanka, bugün nefes al.",
    "Bugün kendine \"yeter artık\" deme kanka, \"biraz daha\" de.",
    "Sen güçlüsün kanka, ben tanığım.",
    "Bugün bir gülümseme dağıt kanka.",
    "Zor günler seni şekillendiriyor kanka, unutma.",
    "Bugün bir adım geri atma kanka, ileri git.",
    "Bugün kendine inanmayan biri varsa kanka, o sen olma.",
    "Sen bugün de ayaktasın kanka, bu bile bir zafer.",
    "Zor olan bitmez ama sen bitmezsin kanka.",
    "Hadi kanka, bugün de mücadele günü.",
    "Sen bugün de buradasın kanka, bu yeter bana.",
    "Zor bir gün geçirdiysen kanka, yarın yeni bir gün.",
    "Bugün bir şeyi tamamla kanka, ne olursa olsun.",
    "Sen bugün de mücadele ettin kanka, farkında mısın?",
    "Zor işleri kolaylaştıran şey sabırdır kanka, sende var.",
    "Bugün kendine güven kanka, ben güveniyorum zaten.",
    "Hadi kanka, bugün de bir şeyler öğren.",
    "Sen bugün de pes etmedin kanka, bu yeterli.",
    "Zor bir gün olabilir kanka ama sen zorlu birisin.",
    "Bugün bir hedefe daha yaklaştın kanka, farkında mısın?",
    "Sen bugün de kalktın kanka, bu bile bir başarı.",
    "Zor günler geçer kanka, sen kalıcısın.",
    "Bugün bir şeyi bırak kanka, bir şeyi başlat.",
    "Hadi kanka, bugün de kendine değer ver.",
    "Sen bugün de savaştın kanka, farkında mısın?",
    "Zor bir hafta geçirdiysen kanka, bugün nefes al.",
    "Sen bugün de ayaktasın kanka, bu bile yeter.",
    "Zor işler seni güçlendirir kanka, unutma.",
    "Bugün bir gülümseme ver kanka, bedava.",
    "Hadi kanka, bugün de bir şeyler kazan.",
    "Sen bugün de mücadele ediyorsun kanka, farkında mısın?",
    "Zor bir gün olabilir kanka ama sen zorluklardan güçlü çıkarsın.",
    "Bugün de mi bahane arıyorsun kanka? Yok böyle bir şey.",
    "Küçük ama sürekli kanka, büyük ama düzensizden iyidir.",
    "Kanka bugün yaptığın, yarının temeli.",
    "Zorlandığın an kanka, ilerlediğin andır.",
    "Bugün de bir adım kanka, yarın bakarsın nerede olduğuna.",
    "İstikrar seni hayal kırıklığına uğratmaz kanka, sen onu uğratma.",
    "Kanka her gün aynı şeyi yapmak sıkıcı ama sonuç değil.",
    "Bugün pes edersen kanka, yarın hikayen yarım kalır.",
    "Zor olan şey değerlidir kanka, unutma.",
    "Bugün kendine iyi bak kanka, kimse senin kadar önemli değil.",
    "Hadi kanka, bugünü dünden iyi yap.",
    "Bugün bir şeyi öğren kanka, küçük de olsa.",
    "Bugün kendine bir söz ver kanka, tut onu.",
    "Kanka bugün de mücadele ettin, gurur duy.",
    "Hadi kanka, bugün de bir şey dene.",
    "Sen bugün de kalktın kanka, farkında mısın?",
    "Kanka bugün kendine bir hediye ver, küçük de olsa.",
    "Zor olsa da kanka, yola devam.",
    "Bugün de mi yorgunsun kanka? Normal, ama vazgeçme.",
    "Kanka bugün bir şey kazandın, kendini fark et.",
    "Sabrın somut hali kanka, istikrardır.",
    "Kanka bugün de mücadeleni sürdürdün.",
    "Hedefe her gün biraz daha yaklaşıyorsun kanka, gör bunu.",
    "Bugün de mi zorlandın kanka? İyi, demek büyüyorsun.",
    "Zor bir gün, seni güçlendiren bir gün kanka.",
    "Kanka bugün de kendine değer verdin.",
    "İstikrarlı olan kanka, sonunda hep kazanır.",
    "Bugün de bir adım kanka, yarın bir tane daha.",
    "Hedefin peşinde olduğun sürece kaybetmezsin kanka.",
    "Kanka her gün biraz daha güçlü bir sen oluyorsun.",
    "Zor olan bırakmak değil kanka, devam etmek.",
    "Bugün de kendine inandın kanka, doğru yaptın.",
    "Kanka bugün kendine bir iyilik yap, biraz nefes al.",
    "Hadi kanka, bugün de rekor kırma günü.",
    "Bugün bir \"hayır\" de kanka, kendine iyilik yap.",
    "Yavaş git ama durma kanka.",
    "Bugün ne olursa olsun kanka, akşam kendine teşekkür et.",
    "Sen bilirsin ama ben hep buradayım kanka.",
    "Bugün bir hedefe bir adım daha yaklaş kanka.",
  ],
  en: [
    "Did you get out of bed, or are you still negotiating with yourself?",
    "Show the world \"I'm here\" again today.",
    "Grab your coffee, make your plan, let's go.",
    "Laziness doesn't love you, buddy — I do.",
    "Take one step, the rest follows on its own.",
    "Today might be tough, but you're tougher.",
    "Get up already, even the sun beat you to it.",
    "Procrastinating's your favorite sport, I know, but not today.",
    "If you don't do it, who will — me?",
    "Just pull off one small win today, that's enough.",
    "Hard days pass, you stick around.",
    "Don't be hard on yourself today, you'll make up for it tomorrow.",
    "Come on buddy, believe in yourself for once too.",
    "Don't say \"I can't\" today, say \"I didn't\" — they're different.",
    "I know you barely slept, but that's no excuse.",
    "You're stronger than you think, I know it.",
    "Put the phone down today, life isn't in there.",
    "Small steps are still steps, don't forget.",
    "If someone treats you badly today, stay good anyway.",
    "Buddy, did you drink your water today, or forget again?",
    "If it's hard, that means you're doing it right.",
    "Don't go to bed today without finishing something.",
    "You don't know how to give up, I do.",
    "\"Well done\" today — you earned it.",
    "You're tired but not done, you know the difference, right?",
    "Smile today, it's free.",
    "Put it off again today, buddy? Fine, tomorrow for sure.",
    "Take a short break, but don't quit.",
    "Do someone a favor today, it'll come back to you.",
    "If you're here today, that means you already won yesterday.",
    "Rough day? I'm right here with you.",
    "Be proud of yourself today, you don't need a reason.",
    "Come on buddy, today's the day you break your record.",
    "Say one \"no\" today, do yourself a favor.",
    "Go slow, just don't stop.",
    "Whatever happens today, thank yourself tonight.",
    "You know best, but I'm always here.",
    "Started the day on your phone again, buddy? It's fine, get up now.",
    "Get one step closer to a goal today.",
    "What's hard is worth it, remember that.",
    "Take good care of yourself today, no one matters as much as you.",
    "Come on, make today better than yesterday.",
    "Learn something today, even if it's small.",
    "You didn't give up, so neither am I.",
    "Buddy, do you remember what your plan was today?",
    "Set aside a little time for yourself today.",
    "If hard work were easy, everyone would do it.",
    "Make yourself a promise today, and keep it.",
    "Come on buddy, you're going to pull something off today too.",
    "Feeling low today? Lean on me, it'll pass.",
    "If you're here today, you're winning the war.",
    "Buddy, did you get up early, or did the alarm drag you up?",
    "If you make a mistake today, fix it and move on.",
    "I know it's been a rough week, breathe today.",
    "Don't tell yourself \"that's enough\" today, say \"a little more.\"",
    "You're strong, I'm a witness to it.",
    "Hand out a smile today.",
    "Buddy, be good to yourself today, you deserve it.",
    "Hard days shape you, don't forget.",
    "Don't take a step back today, move forward.",
    "Come on buddy, you're today's hero.",
    "If someone doesn't believe in you, don't let it be yourself.",
    "You're still standing today, that's already a win.",
    "Buddy, don't neglect your water, your sleep, yourself.",
    "Hard things don't end, but neither do you.",
    "Do yourself a small kindness today.",
    "Come on, today's a day to fight for it too.",
    "You're here again today, that's enough for me.",
    "Buddy, end the day without being angry at yourself.",
    "Had a rough day? Tomorrow's a new one.",
    "Finish something today, no matter what.",
    "Come on buddy, take one more step today.",
    "You struggled through today too, do you realize that?",
    "Buddy, say something nice to yourself today.",
    "Patience makes hard things easier, and you've got it.",
    "Trust yourself today, I already do.",
    "Go on, learn something today too.",
    "You didn't give up again today, that's enough.",
    "Buddy, you've earned yourself a break today.",
    "Today might be tough, but you're built for tough.",
    "You got one step closer to a goal today, notice that?",
    "Come on buddy, I'm watching, go get 'em.",
    "You got up again today, that's an achievement in itself.",
    "Buddy, tell yourself \"I can\" today.",
    "Hard days pass, you're the one who stays.",
    "Drop something today, start something else.",
    "Go on, value yourself today too.",
    "You fought again today, do you realize that?",
    "Buddy, you owe yourself a thank-you today.",
    "Had a rough week? Breathe today.",
    "Take a step today, don't be afraid.",
    "Come on buddy, something's going to change today too.",
    "You're still standing today, that's already enough.",
    "Buddy, take care of yourself today, I'm watching.",
    "Hard work makes you stronger, don't forget.",
    "Give a smile today, it's free.",
    "Go on, win something today too.",
    "You're still fighting today, do you realize that?",
    "Buddy, make yourself a promise today.",
    "Today might be tough, but you come out of hard times stronger.",
    "Come on buddy, something's going to change today.",
    "You're still standing today, and that's already enough.",
    "Buddy, look after yourself today, I'm keeping an eye on you.",
    "Hard things make you stronger, buddy, keep that in mind.",
    "Give the world a smile today, it's free.",
    "Come on, win something today.",
    "You're still in the fight today, buddy, notice that?",
    "Buddy, set yourself a promise for today.",
    "Today might be tough, but you come out of tough days stronger.",
    "Buddy, you're still standing today, and that's something.",
    "Come on buddy, try one small thing today.",
    "Buddy, it's your call, but I'm right here.",
    "I know today was rough, buddy, this too will pass.",
    "Buddy, you're almost there, don't give up.",
    "You're strong, buddy, don't forget that.",
    "Buddy, take care of yourself today.",
    "Come on buddy, take one more step.",
    "Buddy, yesterday was hard too, but you made it through.",
    "You fought today too, buddy, do you notice that?",
    "Buddy, don't leave something unfinished today.",
    "You don't know how to quit, buddy.",
    "Even if you're tired, keep going, buddy.",
    "Look buddy, see? Turns out you could do it.",
    "Win a small victory today, buddy.",
    "Buddy, everyone's fighting something, you're not alone.",
    "Hang in there a little longer, buddy, it's worth it.",
    "Buddy, you got a little closer to a goal today.",
    "Believe in yourself a little, buddy.",
    "Buddy, the hard part isn't quitting, it's continuing.",
    "You're still here today, buddy, that's a win in itself.",
    "Buddy, small steps are still steps.",
    "You're stronger than you think, buddy.",
    "Buddy, try something today, why not.",
    "Almost there, buddy, feel it.",
    "Buddy, what you do today builds tomorrow.",
    "Nobody's perfect, buddy, you don't have to be either.",
    "Not a step back, buddy, always forward.",
    "Buddy, the moment you struggle is the moment you grow.",
    "Don't give up today, buddy, you'll thank yourself tomorrow.",
    "Buddy, patience is sometimes your only weapon.",
    "Making a mistake doesn't make you worthless, buddy.",
    "Buddy, lay one brick today, the building rises on its own.",
    "Keep going even if you don't believe it yet, buddy, belief comes later.",
    "Buddy, tough days test you, and you pass.",
    "Don't leave something unfinished today, buddy.",
    "Tiredness is temporary, buddy, quitting is permanent.",
    "Buddy, make yourself a promise today and keep it.",
    "Small wins deserve celebrating too, buddy.",
    "Buddy, even when you can't see it, you're moving forward.",
    "Hang on a little more today, buddy.",
    "Everyone has their own pace, buddy, go at yours.",
    "Buddy, it's never too late to learn something.",
    "Face one fear today, buddy.",
    "Hard times shape you, buddy, don't forget that.",
    "Buddy, don't compare your journey to anyone else's.",
    "Win a small victory today, buddy, that's enough.",
    "Effort isn't wasted, buddy, it pays off sooner or later.",
    "Buddy, you're someone who says \"we've got this\" — act like it.",
    "Finish one thing today, buddy, no matter how small.",
    "Guide yourself instead of being angry at yourself, buddy.",
    "If you had a rough day, buddy, start fresh tomorrow.",
    "If you're here, buddy, it means you're still fighting.",
    "Buddy, you got one step closer to your goal today.",
    "You don't have to be flawless, buddy, progress is enough.",
    "Sometimes the biggest win is just continuing, buddy.",
    "Be gentle with yourself today, buddy.",
    "Whoever does the hard thing gets a different result, buddy.",
    "Buddy, if you have a goal, get an inch closer to it today.",
    "Don't sell yourself short, buddy, you've done more than you know.",
    "Try something today even if your spirits are low, buddy.",
    "The road might be long, buddy, but you're still walking it.",
    "A small step forward, buddy, beats no step at all.",
    "Trust yourself a little more today, buddy.",
    "Don't let hardship stop you, buddy, just slow you down.",
    "One bad day doesn't mean everything's over, buddy.",
    "You're getting a little better every day, buddy, even when you don't notice.",
    "Don't give up on something today, buddy.",
    "Walk with steady steps, buddy, you don't have to be fast.",
    "Give yourself one more chance, buddy.",
    "If you made a mistake today, buddy, fix it and keep going.",
    "The hard thing is usually the valuable thing, buddy.",
    "You're too strong to quit, buddy.",
    "Do yourself a small kindness today, buddy.",
    "Everyone started somewhere, buddy, so did you.",
    "Take a step today, buddy, don't be afraid.",
    "Time is working in your favor, buddy, be patient.",
    "You're writing your own story, buddy.",
    "Set yourself a goal today, buddy, even a tiny one.",
    "Stopping when you're tired isn't weakness, buddy.",
    "You made it this far, buddy, no turning back now.",
    "Believe you can pull something off today, buddy.",
    "Hardships never end, buddy, but neither do you.",
    "Believing in yourself is sometimes the only starting point, buddy.",
    "One step today, buddy, one more tomorrow.",
    "Small changes make a big difference over time, buddy.",
    "You're tougher than you think, buddy.",
    "You owe yourself a thank-you today, buddy.",
    "If you're going through something hard, buddy, it's temporary.",
    "Trying something, buddy, beats never trying at all.",
    "Stay true to your own path today, buddy.",
    "Everyone's fighting something, buddy, you're not alone.",
    "You got one click closer to a goal today, buddy.",
    "Learn to forgive yourself, buddy, mistakes are human nature.",
    "Keep doing the hard thing, buddy, the easy thing won't grow you.",
    "Buddy, don't let today's task stay half-done.",
    "Even if you can't see the end of the road, buddy, it's leading you somewhere.",
    "Small steps add up to a big distance, buddy.",
    "Find a reason to believe in yourself today, buddy.",
    "Don't let hardships discourage you, buddy, let them strengthen you.",
    "Learn something today, buddy, even something small.",
    "You didn't give up, buddy, so neither will I.",
    "Make some time for yourself today too, buddy.",
    "If hard work were easy, everyone would do it, buddy.",
    "Buddy, promise yourself something today and follow through.",
    "If your spirits are low today, buddy, lean on me, it'll pass.",
    "If you're here today, buddy, it means you're winning the fight.",
    "If you make a mistake today, buddy, fix it and keep going.",
    "I know it was a hard week, buddy, breathe today.",
    "Don't tell yourself \"that's enough\" today, buddy, say \"a little more.\"",
    "You're strong, buddy, I'm the witness.",
    "Hand out a smile today, buddy.",
    "Hard days are shaping you, buddy, don't forget it.",
    "Don't take a step back today, buddy, move forward.",
    "If someone doesn't believe in themselves today, buddy, don't let it be you.",
    "You're still standing today too, buddy, that's a win in itself.",
    "The hard part never ends, buddy, but neither do you.",
    "Come on buddy, today's another day to fight.",
    "You're still here today too, buddy, that's enough for me.",
    "If you had a rough day, buddy, tomorrow's a new one.",
    "Finish something today, buddy, no matter what.",
    "You fought today too, buddy, do you notice?",
    "What makes hard things easier is patience, buddy, and you have it.",
    "Trust yourself today, buddy, I already do.",
    "Come on buddy, learn something today too.",
    "You didn't give up today either, buddy, that's enough.",
    "Today might be tough, buddy, but you're a tough one.",
    "You got closer to a goal today, buddy, do you notice?",
    "You got up today too, buddy, that's an achievement in itself.",
    "Hard days pass, buddy, you're the one who stays.",
    "Drop something today, buddy, start something else.",
    "Come on buddy, value yourself today too.",
    "You kept fighting today too, buddy, notice that.",
    "It's been a rough week, buddy, take a breath today.",
    "You're still standing today too, buddy, that's enough.",
    "Hard work makes you stronger, buddy, don't forget.",
    "Give the world a smile today, buddy, it's free.",
    "Come on buddy, win something today too.",
    "You're still fighting today too, buddy, do you notice?",
    "Today might be tough, buddy, but you come out of tough days stronger.",
    "Making excuses again today, buddy? Not happening.",
    "Small but steady beats big but sloppy, buddy.",
    "Buddy, what you do today is tomorrow's foundation.",
    "The moment you struggle, buddy, is the moment you progress.",
    "One more step today, buddy, tomorrow you'll see how far you've come.",
    "Consistency won't let you down, buddy, don't let it down either.",
    "Buddy, doing the same thing every day is boring, but it's not about the result.",
    "If you quit today, buddy, your story stays unfinished tomorrow.",
    "The hard thing is the valuable thing, buddy, remember that.",
    "Take care of yourself today, buddy, nobody matters as much as you.",
    "Come on buddy, make today better than yesterday.",
    "Learn something today, buddy, even a small thing.",
    "Make yourself a promise today, buddy, and keep it.",
    "Buddy, you kept fighting today too, be proud.",
    "Come on buddy, try something today too.",
    "You got up today too, buddy, do you notice?",
    "Buddy, give yourself a gift today, even a small one.",
    "Even if it's hard, buddy, keep walking.",
    "Tired again today, buddy? Normal, but don't quit.",
    "Buddy, you won something today, notice it.",
    "Patience, made real, buddy, is consistency.",
    "Buddy, you kept up the fight again today.",
    "You're getting a little closer to your goal every day, buddy, see it.",
    "Struggling again today, buddy? Good, that means you're growing.",
    "A hard day, buddy, is a day that makes you stronger.",
    "Buddy, you valued yourself again today.",
    "Whoever stays consistent, buddy, always wins in the end.",
    "A step today, buddy, and another one tomorrow.",
    "As long as you're chasing your goal, buddy, you're not losing.",
    "Buddy, every day you become a little stronger version of yourself.",
  ],
  es: [
    "¿Ya te levantaste de la cama o sigues negociando contigo mismo?",
    "Hoy también dile al mundo \"aquí estoy\".",
    "Toma tu café, haz tu plan, y a darle.",
    "La pereza no te quiere, amigo, yo sí.",
    "Da un paso, lo demás viene solo.",
    "Hoy puede ser difícil, pero tú eres más fuerte que lo difícil.",
    "Levántate ya, hasta el sol se levantó antes que tú.",
    "Postergar es tu deporte favorito, lo sé, pero hoy no.",
    "Si tú no lo haces, ¿quién lo hará, yo?",
    "Logra algo pequeño hoy, con eso basta.",
    "Los días difíciles pasan, tú te quedas.",
    "No te enojes contigo hoy, mañana lo compensas.",
    "Vamos amigo, cree en ti por una vez también.",
    "Hoy no digas \"no puedo\", di \"no lo hice\", son cosas distintas.",
    "Sé que dormiste poco, pero esa no es excusa.",
    "Eres más fuerte de lo que crees, yo lo sé.",
    "Suelta el teléfono hoy, la vida no está ahí.",
    "Los pasos pequeños también son pasos, no lo olvides.",
    "Si alguien te trata mal hoy, tú sigue siendo bueno.",
    "Amigo, ¿tomaste agua hoy o se te olvidó otra vez?",
    "Si se siente difícil, es porque vas bien.",
    "Hoy no te acuestes sin terminar algo.",
    "Tú no sabes rendirte, yo sí lo sé.",
    "Hoy dite \"bien hecho\", te lo ganaste.",
    "Estás cansado pero no acabado, sabes la diferencia, ¿verdad?",
    "Sonríe hoy, es gratis.",
    "¿Otra vez lo postergaste hoy, amigo? Bueno, mañana sí.",
    "Tómate un pequeño descanso, pero no te rindas.",
    "Haz un favor a alguien hoy, se te regresa.",
    "Si hoy estás aquí, ya ganaste desde ayer.",
    "¿Día difícil? Aquí estoy contigo.",
    "Siéntete orgulloso de ti hoy, no necesitas un motivo.",
    "Vamos amigo, hoy es día de romper récords.",
    "Di un \"no\" hoy, hazte un favor.",
    "Ve despacio, pero no te detengas.",
    "Pase lo que pase hoy, agradécete esta noche.",
    "Tú sabes más, pero yo siempre estoy aquí.",
    "¿Otra vez empezaste el día con el teléfono, amigo? No importa, levántate ya.",
    "Acércate un paso más a una meta hoy.",
    "Lo difícil vale la pena, no lo olvides.",
    "Cuídate bien hoy, nadie es tan importante como tú.",
    "Vamos, haz que hoy sea mejor que ayer.",
    "Aprende algo hoy, aunque sea pequeño.",
    "Tú no te rendiste, así que yo tampoco.",
    "Amigo, ¿recuerdas cuál era tu plan hoy?",
    "Dedícate un poco de tiempo hoy.",
    "Si lo difícil fuera fácil, cualquiera lo haría.",
    "Hazte una promesa hoy, y cúmplela.",
    "Vamos amigo, hoy también vas a lograr algo.",
    "¿Bajón hoy? Apóyate en mí, se pasa.",
    "Si hoy estás aquí, estás ganando la batalla.",
    "Amigo, ¿te levantaste temprano o te levantó la alarma a la fuerza?",
    "Si cometes un error hoy, corrígelo y sigue.",
    "Sé que fue una semana difícil, hoy respira.",
    "Hoy no te digas \"ya fue suficiente\", di \"un poco más\".",
    "Eres fuerte, yo soy testigo.",
    "Reparte una sonrisa hoy.",
    "Amigo, sé bueno contigo hoy, te lo mereces.",
    "Los días difíciles te forman, no lo olvides.",
    "Hoy no des un paso atrás, ve hacia adelante.",
    "Vamos amigo, hoy el héroe eres tú.",
    "Si alguien no cree en ti, que no seas tú mismo.",
    "Hoy sigues de pie, eso ya es una victoria.",
    "Amigo, no descuides tu agua, tu sueño, ni a ti mismo.",
    "Lo difícil no se acaba, pero tú tampoco.",
    "Hazte un pequeño favor hoy.",
    "Vamos, hoy también es día de dar batalla.",
    "Hoy también estás aquí, con eso me basta.",
    "Amigo, termina el día sin enojarte contigo.",
    "¿Tuviste un día difícil? Mañana es un día nuevo.",
    "Termina algo hoy, pase lo que pase.",
    "Vamos amigo, da un paso más hoy.",
    "Hoy también luchaste, ¿te das cuenta?",
    "Amigo, dite algo bonito hoy.",
    "La paciencia hace fácil lo difícil, y tú la tienes.",
    "Confía en ti hoy, yo ya confío.",
    "Anda, aprende algo hoy también.",
    "Hoy tampoco te rendiste, con eso basta.",
    "Amigo, hoy te ganaste un descanso.",
    "Hoy puede ser difícil, pero tú eres de los duros.",
    "Hoy te acercaste un paso más a una meta, ¿te diste cuenta?",
    "Vamos amigo, hoy te estoy vigilando, ve con todo.",
    "Hoy también te levantaste, eso ya es un logro.",
    "Amigo, hoy dite \"yo puedo\".",
    "Los días difíciles pasan, tú permaneces.",
    "Hoy suelta algo, empieza algo nuevo.",
    "Anda, hoy también valórate a ti mismo.",
    "Hoy también peleaste tu batalla, ¿te das cuenta?",
    "Amigo, hoy te debes un agradecimiento.",
    "¿Tuviste una semana difícil? Hoy respira.",
    "Da un paso hoy, sin miedo.",
    "Vamos amigo, hoy también algo va a cambiar.",
    "Hoy sigues de pie, con eso basta.",
    "Amigo, cuídate hoy, te estoy vigilando.",
    "Lo difícil te hace más fuerte, no lo olvides.",
    "Regala una sonrisa hoy, es gratis.",
    "Anda, hoy también gana algo.",
    "Hoy sigues luchando, ¿te das cuenta?",
    "Amigo, hazte una promesa hoy.",
    "Hoy puede ser difícil, pero tú sales más fuerte de las dificultades.",
    "Vamos amigo, hoy algo va a cambiar.",
    "Sigues en pie hoy, y eso ya es suficiente.",
    "Amigo, cuídate hoy, te estoy vigilando de cerca.",
    "Lo difícil te vuelve más fuerte, amigo, no lo olvides.",
    "Reparte una sonrisa hoy, es gratis.",
    "Vamos, gana algo hoy.",
    "Sigues luchando hoy, ¿te das cuenta?",
    "Amigo, prométete algo hoy mismo.",
    "Hoy puede ser difícil, pero de los días difíciles sales más fuerte.",
    "Amigo, sigues en pie hoy, y eso ya es algo.",
    "Vamos amigo, intenta algo pequeño hoy.",
    "Amigo, tú decides, pero yo estoy aquí.",
    "Sé que hoy fue duro, amigo, esto también pasará.",
    "Amigo, ya casi llegas, no te rindas.",
    "Eres fuerte, amigo, no lo olvides.",
    "Amigo, cuídate hoy.",
    "Vamos amigo, da un paso más.",
    "Amigo, ayer también te costó, pero lo lograste.",
    "Hoy también luchaste, amigo, ¿te das cuenta?",
    "Amigo, no dejes algo a medias hoy.",
    "No sabes rendirte, amigo.",
    "Aunque estés cansado, sigue adelante, amigo.",
    "Mira amigo, ¿ves? Sí podías.",
    "Gana una pequeña victoria hoy, amigo.",
    "Amigo, todos tienen su propia lucha, no estás solo.",
    "Aguanta un poco más, amigo, vale la pena.",
    "Amigo, hoy te acercaste un poco más a una meta.",
    "Cree un poco en ti mismo, amigo.",
    "Amigo, lo difícil no es rendirse, es seguir.",
    "Sigues aquí hoy, amigo, y eso ya es una victoria.",
    "Amigo, los pasos pequeños también son pasos.",
    "Eres más fuerte de lo que crees, amigo.",
    "Amigo, intenta algo hoy, nunca se sabe.",
    "Ya casi, amigo, siéntelo.",
    "Amigo, lo que haces hoy construye el mañana.",
    "Nadie es perfecto, amigo, tú tampoco tienes que serlo.",
    "Ni un paso atrás, amigo, siempre hacia adelante.",
    "Amigo, el momento en que luchas es el momento en que creces.",
    "No te rindas hoy, amigo, mañana te lo agradecerás.",
    "Amigo, a veces la paciencia es tu única arma.",
    "Equivocarte no te hace menos valioso, amigo.",
    "Amigo, pon un ladrillo hoy, el edificio se levanta solo.",
    "Sigue aunque no lo creas todavía, amigo, la fe llega después.",
    "Amigo, los días difíciles te ponen a prueba, y tú los superas.",
    "No dejes algo a medias hoy, amigo.",
    "El cansancio es pasajero, amigo, rendirse es para siempre.",
    "Amigo, hazte una promesa hoy y cúmplela.",
    "Los pequeños logros también merecen celebrarse, amigo.",
    "Amigo, aunque no lo veas, estás avanzando.",
    "Aguanta un poco más hoy, amigo.",
    "Cada quien tiene su propio ritmo, amigo, sigue el tuyo.",
    "Amigo, nunca es tarde para aprender algo.",
    "Enfrenta un miedo hoy, amigo.",
    "Los momentos difíciles te forman, amigo, no lo olvides.",
    "Amigo, no compares tu camino con el de nadie más.",
    "Gana una pequeña victoria hoy, amigo, con eso basta.",
    "El esfuerzo no se pierde, amigo, tarde o temprano da fruto.",
    "Amigo, eres de los que dicen \"lo lograremos\" — actúa así.",
    "Termina algo hoy, amigo, por pequeño que sea.",
    "En vez de enojarte contigo, guíate, amigo.",
    "Si tuviste un mal día, amigo, empieza de nuevo mañana.",
    "Si estás aquí, amigo, es porque sigues luchando.",
    "Amigo, hoy diste un paso más hacia tu meta.",
    "No tienes que ser perfecto, amigo, con avanzar basta.",
    "A veces el mayor logro es simplemente continuar, amigo.",
    "Sé amable contigo mismo hoy, amigo.",
    "Quien hace lo difícil obtiene un resultado diferente, amigo.",
    "Amigo, si tienes una meta, acércate un poco más hoy.",
    "No te subestimes, amigo, has logrado más de lo que crees.",
    "Intenta algo hoy aunque estés desanimado, amigo.",
    "El camino puede ser largo, amigo, pero sigues caminando.",
    "Un pequeño avance, amigo, es mejor que ninguno.",
    "Confía un poco más en ti hoy, amigo.",
    "No dejes que lo difícil te detenga, amigo, solo que te frene un poco.",
    "Un mal día no significa que todo terminó, amigo.",
    "Cada día mejoras un poco, amigo, aunque no lo notes.",
    "No abandones algo hoy, amigo.",
    "Camina con pasos firmes, amigo, no tienes que ser rápido.",
    "Date una oportunidad más, amigo.",
    "Si te equivocaste hoy, amigo, corrígelo y sigue.",
    "Lo difícil suele ser lo valioso, amigo.",
    "Eres demasiado fuerte para rendirte, amigo.",
    "Hazte un pequeño favor hoy, amigo.",
    "Todos empezaron desde algún lugar, amigo, tú también.",
    "Da un paso hoy, amigo, no tengas miedo.",
    "El tiempo está de tu lado, amigo, ten paciencia.",
    "Tú escribes tu propia historia, amigo.",
    "Ponte una meta hoy, amigo, aunque sea pequeña.",
    "Parar cuando estás cansado no es debilidad, amigo.",
    "Llegaste hasta aquí, amigo, ya no hay vuelta atrás.",
    "Cree que puedes lograr algo hoy, amigo.",
    "Las dificultades no terminan, amigo, pero tú tampoco.",
    "Creer en ti mismo a veces es el único punto de partida, amigo.",
    "Un paso hoy, amigo, otro mañana.",
    "Los pequeños cambios hacen una gran diferencia con el tiempo, amigo.",
    "Eres más resistente de lo que crees, amigo.",
    "Hoy te debes un agradecimiento, amigo.",
    "Si estás pasando por algo difícil, amigo, es temporal.",
    "Intentar algo, amigo, es mejor que nunca intentarlo.",
    "Sé fiel a tu camino hoy, amigo.",
    "Todos tienen su propia lucha, amigo, no estás solo.",
    "Hoy te acercaste un poco más a una meta, amigo.",
    "Aprende a perdonarte, amigo, equivocarse es humano.",
    "Sigue haciendo lo difícil, amigo, lo fácil no te hace crecer.",
    "Amigo, no dejes nada a medio terminar hoy.",
    "Aunque no veas el final del camino, amigo, te está llevando a algún lugar.",
    "Los pequeños pasos suman una gran distancia, amigo.",
    "Busca una razón para creer en ti hoy, amigo.",
    "No dejes que las dificultades te desanimen, amigo, que te fortalezcan.",
    "Aprende algo hoy, amigo, aunque sea pequeño.",
    "Tú no te rendiste, amigo, así que yo tampoco.",
    "Date también un poco de tiempo hoy, amigo.",
    "Si lo difícil fuera fácil, todos lo harían, amigo.",
    "Amigo, prométete algo hoy y no lo dejes en promesa.",
    "Si hoy estás desanimado, amigo, apóyate en mí, esto pasará.",
    "Si estás aquí hoy, amigo, significa que estás ganando la batalla.",
    "Si te equivocas hoy, amigo, corrígelo y sigue.",
    "Sé que fue una semana dura, amigo, respira hoy.",
    "Hoy no te digas \"ya es suficiente\", amigo, di \"un poco más\".",
    "Eres fuerte, amigo, yo soy testigo.",
    "Reparte una sonrisa hoy, amigo.",
    "Los días difíciles te están formando, amigo, no lo olvides.",
    "No des un paso atrás hoy, amigo, avanza.",
    "Si alguien no cree en sí mismo hoy, amigo, que no seas tú.",
    "Hoy también sigues en pie, amigo, eso ya es una victoria.",
    "Lo difícil nunca termina, amigo, pero tú tampoco.",
    "Vamos amigo, hoy es otro día para luchar.",
    "Hoy también sigues aquí, amigo, con eso me basta.",
    "Si tuviste un mal día, amigo, mañana es uno nuevo.",
    "Termina algo hoy, amigo, pase lo que pase.",
    "Hoy también seguiste peleando, amigo, ¿lo notas?",
    "Lo que hace más fácil lo difícil es la paciencia, amigo, y tú la tienes.",
    "Confía en ti hoy, amigo, yo ya confío.",
    "Vamos amigo, aprende algo hoy también.",
    "Hoy tampoco te rendiste, amigo, con eso basta.",
    "Hoy puede ser difícil, amigo, pero tú eres de los duros.",
    "Hoy te acercaste a una meta, amigo, ¿te das cuenta?",
    "Hoy también te levantaste, amigo, eso ya es un logro.",
    "Los días difíciles pasan, amigo, tú te quedas.",
    "Deja algo hoy, amigo, empieza otra cosa.",
    "Vamos amigo, hoy también valórate.",
    "Hoy también seguiste luchando, amigo, date cuenta.",
    "Fue una semana difícil, amigo, respira hoy.",
    "Hoy también sigues en pie, amigo, con eso basta.",
    "Lo difícil te hace más fuerte, amigo, no lo olvides.",
    "Regala una sonrisa hoy, amigo, es gratis.",
    "Vamos amigo, gana algo hoy también.",
    "Hoy también sigues luchando, amigo, ¿te das cuenta?",
    "Hoy puede ser difícil, amigo, pero de los días difíciles sales más fuerte.",
    "¿Otra vez buscando excusas hoy, amigo? Eso no existe.",
    "Pequeño pero constante, amigo, es mejor que grande pero desordenado.",
    "Amigo, lo que haces hoy es la base de mañana.",
    "El momento en que luchas, amigo, es el momento en que avanzas.",
    "Un paso más hoy, amigo, mañana verás lo lejos que llegaste.",
    "La constancia no te va a fallar, amigo, no le falles tú a ella.",
    "Amigo, hacer lo mismo cada día es aburrido, pero no se trata del resultado.",
    "Si te rindes hoy, amigo, tu historia queda a medias mañana.",
    "Lo difícil es lo valioso, amigo, no lo olvides.",
    "Cuídate hoy, amigo, nadie es tan importante como tú.",
    "Vamos amigo, haz que hoy sea mejor que ayer.",
    "Aprende algo hoy, amigo, por pequeño que sea.",
    "Hazte una promesa hoy, amigo, y cúmplela.",
    "Amigo, hoy también seguiste luchando, siéntete orgulloso.",
    "Vamos amigo, intenta algo hoy también.",
    "Hoy también te levantaste, amigo, ¿te das cuenta?",
    "Amigo, date un regalo hoy, aunque sea pequeño.",
    "Aunque sea difícil, amigo, sigue el camino.",
    "¿Otra vez cansado hoy, amigo? Normal, pero no te rindas.",
    "Amigo, hoy ganaste algo, date cuenta.",
    "La paciencia hecha realidad, amigo, es la constancia.",
    "Amigo, hoy también mantuviste la lucha.",
    "Cada día te acercas un poco más a tu meta, amigo, mira eso.",
    "¿Otra vez te costó hoy, amigo? Bien, significa que estás creciendo.",
    "Un día difícil, amigo, es un día que te fortalece.",
    "Amigo, hoy también te valoraste.",
    "Quien es constante, amigo, siempre gana al final.",
    "Hoy un paso, amigo, y otro más mañana.",
    "Mientras persigas tu meta, amigo, no estás perdiendo.",
    "Amigo, cada día te vuelves una versión un poco más fuerte de ti mismo.",
  ],
};

const streak_reminder = {
  tr: 'Serini kaçırmak üzeresin! Bugünü işaretlemeyi unutma kanka.',
  en: 'You\'re about to lose your streak! Don\'t forget to check off today, buddy.',
  es: '¡Estás a punto de perder tu racha! No olvides marcar el día de hoy, amigo.',
};

const daily_reward = {
  tr: 'Bugünün ödülünü almadın! Günlük Giriş Ödülü seni bekliyor.',
  en: 'You haven\'t claimed today\'s reward yet! Your Daily Login Reward is waiting.',
  es: '¡Todavía no reclamaste el premio de hoy! Tu Recompensa Diaria te está esperando.',
};

const re_engagement = {
  tr: 'Seni özledim kanka, bir bakıver ne yaptığına 🧡',
  en: 'I miss you buddy, come take a look at what you\'ve been up to 🧡',
  es: 'Te extraño amigo, ven a ver qué has estado haciendo 🧡',
};

const water_reminder = {
  tr: 'Suyunu içtin mi kanka? Hemen bir bardak iç, hedefine bir adım daha yaklaş! 💧',
  en: 'Did you drink your water, buddy? Have a glass now, one step closer to your goal! 💧',
  es: '¿Tomaste agua, amigo? Bebe un vaso ahora, un paso más cerca de tu meta! 💧',
};

module.exports = {
  daily_motivation,
  streak_reminder,
  daily_reward,
  re_engagement,
  water_reminder,
};
